branch-defaults:
  default:
    environment: WholepoolWebProduction-env
    group_suffix: null
deploy:
  artifact: target/wholepool-web-1.0.0.jar
global:
  application_name: wholepool-web-production
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
