branch-defaults:
  default:
    environment: wholepool-rest-env
environment-defaults:
  wholepool-rest-env:
    branch: null
    repository: null
global:
  application_name: wholepool-rest
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-3::platform/Java 8 running on
    64bit Amazon Linux/2.7.6
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
